/**
 * Stable machine-readable error codes (F5). The frontend translates these through
 * `errors.<code>` (H7), so never rename one: add a new code instead.
 */
export const ErrorCode = {
  // generic, derived from the HTTP status when no specific code applies
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // authentication / authorisation
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TENANT_MISMATCH: 'TENANT_MISMATCH',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',
  OWNER_REQUIRED: 'OWNER_REQUIRED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  TENANT_CLOSED: 'TENANT_CLOSED',

  // plans and billing (section I)
  PLAN_LIMIT_REACHED: 'PLAN_LIMIT_REACHED',
  PLAN_FEATURE_UNAVAILABLE: 'PLAN_FEATURE_UNAVAILABLE',
  SUBSCRIPTION_PAST_DUE: 'SUBSCRIPTION_PAST_DUE',
  NO_ACTIVE_SUBSCRIPTION: 'NO_ACTIVE_SUBSCRIPTION',
  INVALID_SUBSCRIPTION_STATE: 'INVALID_SUBSCRIPTION_STATE',
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',

  // resources
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  INVITE_NOT_FOUND: 'INVITE_NOT_FOUND',
  LOCALE_NOT_FOUND: 'LOCALE_NOT_FOUND',
  NAMESPACE_NOT_FOUND: 'NAMESPACE_NOT_FOUND',

  // conflicts
  SLUG_TAKEN: 'SLUG_TAKEN',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  EXTERNAL_ID_TAKEN: 'EXTERNAL_ID_TAKEN',
  LAST_OWNER: 'LAST_OWNER',
  TENANT_HAS_DEPENDENCIES: 'TENANT_HAS_DEPENDENCIES',

  // single-use links (invite, password reset, email verification)
  INVITE_INVALID: 'INVITE_INVALID',
  RESET_TOKEN_INVALID: 'RESET_TOKEN_INVALID',
  VERIFICATION_TOKEN_INVALID: 'VERIFICATION_TOKEN_INVALID',

  // infrastructure
  MAIL_DELIVERY_FAILED: 'MAIL_DELIVERY_FAILED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
